#!/usr/bin/osascript

-- Remotely Control the Volume on Your Mac
--
-- *** INSTRUCTIONS ***
--
-- to run:  sh remote_vol_adjust [ARG]
--
-- options: mute            mutes the computer
--          unmute          unmutes
--          x               between -100 and 100
--                          changes the volume by x percent
--

on run argv
    
    -- get the user's command
    set command to (item 1 of argv)

    -- mute volume
    if command is equal to "mute" then 
        
        set _muted to (get (output muted of (get volume settings)))
        
        if _muted is false then
            set volume with output muted
        else
            set volume without output muted
        end if

    -- unmute volume
    else if command is equal to "unmute" then

        set volume without output muted

    else

        -- only process input that is a valid integer
        try

            set adjust_by to command as integer
            adjust_volume(adjust_by)

        end try

    end tell

end run

on adjust_volume(adjust_by)

    set vol to output volume of (get volume settings)
    set volume output volume (vol + adjust_by)

end adjust_volume